backend = "kmeans"
color_space = "lch"
palette = "harddark"
check_contrast = true
saturation = 50

[templates]
kitty = { template = 'kitty.conf', target = '~/.config/kitty/current-theme.conf' }
waybar = { template = 'waybar.css', target = '~/.config/waybar/colors.css' }
discord = { template = 'discord.css', target = '~/.cache/wallust/discord.css' }